[workspace]
resolver = "2"
members = ["nes"]

[package]
name = "rustyness"
version = "0.1.0"
edition = "2021"

[dependencies]
nes = { version = "0.1.0", path = "nes" }

[profile.dev]
overflow-checks = false
